maintainer       "Alex Howells"
maintainer_email "alex@howells.me"
license          "Apache 2.0"
description      "Manage OSX application and system settings"
version          "2.0.0"
depends		 "stdlib"
supports         "mac_os_x"
